---
roles:
  - src: andrewrothstein.k9s
    version: v2.1.13
  - src: andrewrothstein.krew
    version: v1.2.0
  - src: andrewrothstein.kubernetes_helm
    version: 3.0.17
  - src: andrewrothstein.opentofu
    version: 1.0.9
  - src: andrewrothstein.powershell
    version: v1.2.2
  - src: andrewrothstein.terraform
    version: v3.0.38
  - src: geerlingguy.docker
    version: 7.4.3
  - src: bbaassssiiee.kubeblocks
    version: 1.0.5
  - src: bbaassssiiee.nginx_ssl
    version: 1.0.5
  - src: bbaassssiiee.postgres_ssl
    version: 1.1.0
  - src: bbaassssiiee.proxy
    version: 1.0.3
