---
postgres_enabled: true
postgres_version: 15
# Postgresql users and databases/schemas
database:
  postgres:
    name: postgres
    owner: postgres
    username: postgres
    password: "{{ lookup('env', 'DB_PASS') }}"
    enabled: true
  semaphore:
    name: semaphore
    owner: semaphore
    username: semaphore
    password: "{{ lookup('env', 'DB_PASS') }}"
    enabled: true
